### PR TITLE
Add Google Analytics

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by dberzano** [comment]
OK so it looks Travis CI has caught an error:

```
Traceback (most recent call last):
  File "alibuild/aliBuild", line 1272, in <module>
    os.environ["ALIBUILD_VERSION"] = getVersion()
  File "/home/travis/build/alisw/alibuild/alibuild_helpers/utilities.py", line 54, in getVersion
    cmd = "GIT_DIR=\'%s/.git\' git describe --tags" % dirname(__file__)
NameError: global name 'dirname' is not defined
```

**Comment by ktf** [comment]
Should be fixed now.

**Comment by dberzano** [comment]
Impeccable 👍

**Comment by ktf** [comment]
There is actually one last thing we should do:

```
aliBuild analytics on
aliBuild analytics off
```

**Pull request merged**
