### PR TITLE
Do not let the printer do the formatting

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr @pzhristov can you see if this fixes your issue?

**Comment by davidrohr** [comment]
@ktf : thx, this fixes #660

**Comment by pzhristov** [comment]
Yes, it does, but now I have other problems in the installation of AliPhysics - some libraries from AliRoot are not found. Not sure if it has to do with the same issue.

**Comment by ktf** [comment]
Timo's fix is actually more complete.

**Pull request closed without merging**
