### PR TITLE
Do not prune _VERSION vars if not in alienv

### LINKED ISSUE #530: alibuild_helpers.utilities.prunePaths undefines essential Cray PE environment variables
Running `aliBuild build` on Cray XC40, with Cray PE installed, fails with missing packages that are however properly installed. And interestingly, `aliBuild doctor` is able to successfully pick up those packages. Porting the diagnostic code from `alibuild_helpers.doctor` into `alibuild_helpers.build` reveals that the failure is (and similarly, for `Xdevel`, `curl`, and `libperl`):

```
ERROR: Package opengl is a system requirement and cannot be found.
ERROR: This is due to the fact that the following script fails:
ERROR: 
ERROR: brew() { true; }; printf "#include <GL/glu.h>\n" | cc -xc - -c -o /dev/null
ERROR: with the following output:
ERROR: 
ERROR: opengl: Error:
ERROR: opengl: Unable to determine compiler version.
ERROR: opengl: Make sure that a gnu module is loaded and that GNU_VERSION is defined
ERROR: opengl: 
ERROR: OpenGL development packages are missing on your system.
ERROR:   * On RHEL-compatible systems you probably need: mesa-libGLU-devel
ERROR:   * On Ubuntu-compatible systems you probably need: libglu1-mesa-dev
ERROR: 
ERROR: 
```
It turns out only `alibuild_helpers.build.doBuild` additionally calls `alibuild_helpers.utilities.prunePaths`, which clears any environment variable ending in `_VERSION` (with the `ALIBUILD_VERSION` as exception), that also unsets various `*_VERSION` that the Cray PE needs to function:

```
CRAYPE_VERSION
CRAY_LIBSCI_VERSION
DVS_VERSION
GCC_VERSION
GNU_VERSION
INTEL_MAJOR_VERSION
INTEL_MINOR_VERSION
INTEL_VERSION
LIBSCI_VERSION
```

### PR DESCRIPTION
**Pull request by dberzano**
Fixes #530.

### CODE REVIEW

**Comment by ktf** [comment]
Is that what we really want? Shouldn't messing up `*_VERSION` be forbidden also when not under alienv?

**Comment by dberzano** [comment]
In principle we don't ever want to mess with the user's environment. We only want to clean up `_VERSION` variables to prevent aliBuild misbehaviours when inside an `alienv` environment, I see no other case where we should clean up variables ending with `_VERSION` (which is a quite generic suffix).

**Comment by dberzano** [comment]
Yes but you realize that this implies rewriting the entirety of our recipes? This is absolutely not what I want to do! :-)

**Comment by ktf** [comment]
Yes, but this change will open a potential can of worms for currently working setup. We added the pruning of version because we did have the problem I indicate above, IIRC.

Alternatively we could change recipes to use `<SOMETHING>_REVISION` to detect alibuild built packages, but that also implies changing recipes (albeit in a compatible way).

**Comment by Barthelemy** [comment]
should we close this PR ?

**Comment by ktf** [comment]
Yes, given we are finally switching to `_REVISION`.

**Pull request closed without merging**
