### PR TITLE
Fix for alienv with modules >= 4.0 plus minor improvements

### PR DESCRIPTION
**Pull request by dberzano**
* New modules repository: https://github.com/cea-hpc/modules
* See also https://modules.readthedocs.io/en/latest/MIGRATING.html

### CODE REVIEW

**Comment by dberzano** [comment]
@Barthelemy @ktf this should be robust enough to tolerate modules 4.0.0 on Linuxes too.

**Comment by Barthelemy** [comment]
ok thank you. Do you need me to test it ? If so, I don't know how to update alibuild to your version.

**Comment by dberzano** [comment]
Hi @Barthelemy, if you want to test it:

```
pip install git+https://github.com/dberzano/alibuild@fix-alienv-modules --upgrade
```

Prepend `sudo` if you did it in the first place. A normal:

```
pip install alibuild --upgrade
```

will restore your previous installation afterwards.

**Comment by Barthelemy** [comment]
ok it works

**Pull request merged**
