### PR TITLE
Minor fixes for weird characters in logs and RHEL auto-detect.

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy this should take care of your issue with RHEL6.

**Comment by Barthelemy** [comment]
To answer your question in the email, this is not RHEL6 but SLC6. I get the same output on lxplus : 

> -bash-4.1$ python -c "import platform ; print platform.dist()" 
> ('redhat', '6.7', 'Carbon')

**Comment by ktf** [comment]
I understand. It's the docker images we use for the builds which are actually centos . Anyways, can you confirm this fixes the issue?

**Comment by Barthelemy** [comment]
I will try it tomorrow.

**Comment by Barthelemy** [comment]
It works.

**Pull request merged**
