### PR TITLE
Experimental support for S3 repositories [O2-1010]

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
This will also require `s3cmd` as a dependency.

**Comment by ktf** [comment]
@alisw/o2-wp3 this should allow caching of dependencies on macOS. To try it out:

```bash
brew tap alisw/system-deps
brew reinstall alisw/system-deps/alibuild
git clone -b s3-repositories https://github.com/ktf/alibuild
alibuild/aliBuild build boost --remote-store s3://alibuild-repo$WRITE --debug
```

can you all try it out and provide feedback? I guess it will only work on Catalina because that's what I am using.

**Comment by ktf** [comment]
@mpuccio

**Comment by ktf** [comment]
Merging this as the feature is only enabled when using `s3://` as prefix for the `--remote-store` option. Seems to work well in my tests, plenty of packages already populated at:

https://s3.cern.ch/swift/v1/alibuild-repo/

and build time drastically reduced.

**Comment by Barthelemy** [comment]
I get the following error : 
```
bvonhall@macbookairbarth alice $ alibuild/aliBuild build boost --remote-store s3://alibuild-repo --debug
DEBUG: Building for architecture osx_x86-64
DEBUG: Number of parallel builds: 8
DEBUG: Using aliBuild from alibuild@844818fd61c457c3f1fca7c663c3e79d6ac3ed40 recipes in alidist@e164dbde06004bbac618b0131102ed5fc5dc2832
ERROR: In recipe "bz2": version must be a string
```

**Comment by ktf** [comment]
Mmmmm... Did you update alidist? the hash seems wrong.

**Comment by sawenzel** [comment]
Nice progress! I am wondering for which version of MacOS will this work? Should we introduce some tag/version in the file path to prevent incompatibilities?

**Comment by ktf** [comment]
In principle we should be able to make it work on any reasonably old mac with one set of  binaries. It should be just a matter of exporting `MACOSX_DEPLOYMENT_PLATFORM=10.12` when we build. We should probably also embed that in the package hash, so that when we move our support window we get a separate set of packages. That said, IIRC, between Mohave and Catalina things should just work.

**Comment by sawenzel** [comment]
Ok

**Comment by ktf** [comment]
BTW, this actually paves the way to ubuntu binaries...

**Comment by Barthelemy** [comment]
Even with an up to date alidist I get this : 
```
bvonhall@macbookairbarth alice $  alibuild/aliBuild build boost --remote-store s3://alibuild-repo --debug
DEBUG: Building for architecture osx_x86-64
DEBUG: Number of parallel builds: 8
DEBUG: Using aliBuild from alibuild@844818fd61c457c3f1fca7c663c3e79d6ac3ed40 recipes in alidist@34529d6f923becf8ef830ca11e65a2ff202ed4c2
ERROR: In recipe "bz2": version must be a string
```

**Comment by ktf** [comment]
Very weird. Maybe an old version of PyYAML? anyways:

https://github.com/alisw/alidist/pull/1984

should fix it. Can you cherrypick and try again?

**Comment by Barthelemy** [comment]
Here is a PR with other missing quotes : https://github.com/alisw/alidist/pull/1985

When I run now, it asks for a password : 
```
bvonhall@macbookairbarth alice $ alibuild/aliBuild build boost --remote-store s3://alibuild-repo --debug
DEBUG: Building for architecture osx_x86-64
DEBUG: Number of parallel builds: 8
DEBUG: Using aliBuild from alibuild@844818fd61c457c3f1fca7c663c3e79d6ac3ed40 recipes in alidist@e11ae0bbd2f2e352d3bc25c453b11258916b8800


DEBUG: Main package is boost@v1.70.0
DEBUG:boost:v1.70.0: Commit hash for https://github.com/alisw/alien-cas.git@bcb18b10f695dbfe85599b7bbb5452720a91dddd is bcb18b10f695dbfe85599b7bbb5452720a91dddd
DEBUG:boost:v1.70.0: Commit hash for https://github.com/star-externals/zlib@v1.2.8 is v1.2.8
DEBUG:boost:v1.70.0: Commit hash for https://github.com/alisw/autotools@v1.5.0 is v1.5.0
DEBUG:boost:v1.70.0: Commit hash for https://github.com/Kitware/CMake@v3.13.1 is v3.13.1
DEBUG:boost:v1.70.0: Commit hash for https://github.com/alisw/liblzma@v5.2.3 is v5.2.3
DEBUG:boost:v1.70.0: Commit hash for https://gitlab.gnome.org/GNOME/libxml2.git@v2.9.3 is v2.9.3
DEBUG:boost:v1.70.0: Commit hash for https://github.com/alisw/apmon-cpp.git@v2.2.8-alice2 is v2.2.8-alice2
DEBUG:boost:v1.70.0: Commit hash for https://github.com/alisw/uuid@alice/v2.27.1 is a24d32e00da30c78ace5a0786d8c1777f2636a61
DEBUG:boost:v1.70.0: Commit hash for https://github.com/alisw/libpng@v1.6.34 is v1.6.34
DEBUG:boost:v1.70.0: Commit hash for https://github.com/alisw/boost.git@v1.70.0 is v1.70.0
DEBUG:boost:v1.70.0: Calculating hashes.
DEBUG:boost:v1.70.0: Hash for recipe defaults-release is b26492899c1e2d33f37764947e600564531ea2cb
DEBUG:boost:v1.70.0: Hash for recipe AliEn-CAs is af64603866098a1d9df4c9c320374bf8c2d6c4a1
DEBUG:boost:v1.70.0: Hash for recipe termcap is 08aeef432354db5b84ab32cdb51a79260c501ff5
DEBUG:boost:v1.70.0: Hash for recipe bz2 is 20c252fe7f8cd8eb93a449a4c2bc94865265093c
DEBUG:boost:v1.70.0: Hash for recipe make is 0cc45a4de5b4408ade3847ea1dbcfcd4fd94e87d
DEBUG:boost:v1.70.0: Hash for recipe zlib is 9adfba8acdf4eabb260bc47908580cf637e0cb61
DEBUG:boost:v1.70.0: Hash for recipe osx-system-openssl is e2e4fa46db89717e59b9785ddaba3ab69ee9847b
DEBUG:boost:v1.70.0: Hash for recipe Xcode is 34e5e835100f5a267f58bc34797f3d51ceab3cc1
DEBUG:boost:v1.70.0: Hash for recipe autotools is 6927a7f0a1bcd96f49475226c2d61382900c3da2
DEBUG:boost:v1.70.0: Hash for recipe CMake is 1e94d74b610c319eac400e451adccb8fb2422c42
DEBUG:boost:v1.70.0: Hash for recipe lzma is 13778c7196b952821380344aac19bfbaf7d07f41
DEBUG:boost:v1.70.0: Hash for recipe libxml2 is 7dd88a6a681a65ca822d6a57be16db54b94d831e
DEBUG:boost:v1.70.0: Hash for recipe ApMon-CPP is e470defe1c1e5e9ecf3fc132826582e6197f999c
DEBUG:boost:v1.70.0: Hash for recipe UUID is a62fb5c982a6852eaa233bc7858c5125dc0c2577
DEBUG:boost:v1.70.0: Hash for recipe AliEn-Runtime is 33a2fcc7209a06faf405b5cbc899d323c82370e2
DEBUG:boost:v1.70.0: Hash for recipe libpng is 53bcd1849a62df2ad3fd728ccc38e192bcdb6eaa
DEBUG:boost:v1.70.0: Hash for recipe boost is 8d44e2b26ff41d5c7393ac684ddb6bc5ab324dc6
DEBUG:boost:v1.70.0: We will build packages in the following order: %s
DEBUG:boost:v1.70.0: Updating from tarballs
DEBUG:boost:v1.70.0: Updating remote store for package defaults-release@b26492899c1e2d33f37764947e600564531ea2cb
Password: 
```

**Comment by ktf** [comment]
can you do:

```
cd alibuild
git show
```

the password gets asked if you are using the old version...

**Comment by Barthelemy** [comment]
```
bvonhall@macbookairbarth alibuild (master) $ git show
commit 844818fd61c457c3f1fca7c663c3e79d6ac3ed40 (HEAD -> master, origin/master, origin/HEAD)
Merge: 1dc2af9 0ea9342
Author: Giulio Eulisse <giulio.eulisse@cern.ch>
Date:   Mon Apr 11 20:44:39 2016 +0200

    Merge pull request #190 from ktf/master
    
    Add Jenkinsfile for alibuild
```

**Comment by Barthelemy** [comment]
it might be because you instructed to use alibuild/alibuild instead of alisw/alibuild ?

**Comment by ktf** [comment]
yes. I did not even know about `alibuild/alibuild`.

**Comment by Barthelemy** [comment]
ok, now it works !

**Pull request merged**
