### PR TITLE
Migrate to mkdocs

### PR DESCRIPTION
**Pull request by singiamtel**
Migrate from Jekyll to [mkdocs](https://www.mkdocs.org/). The main feature we want from mkdocs is the search bar

I've tried to keep all the old links working, but there may be some that are broken. If you find any, please let me know.

The style is from https://config.docs.cern.ch/

- [X] Migrate from Jekyll to mkdocs
- [ ] Setup GH actions auto deployment
- [ ] Fix docs tests

To try it, install the dependencies and run ``mkdocs serve``

```bash
# dependencies
pip install mkdocs mkdocs-material mkdocs-markdownextradata-plugin mkdocs-redirects
```

### CODE REVIEW

**Comment by ktf** [comment]
Do you have an example of the result?

**Comment by singiamtel** [comment]
I have it running under ali-ci-desktop.cern.ch if you want to try it. Currently looks like this 

image

I'll try to finish the CI and tests tomorrow

**Comment by ktf** [comment]
I reverted this assuming it was accidental.

**Comment by singiamtel** [comment]
Yeah it was, sorry

I'll re-open a new one

**Comment by ktf** [comment]
no worries.

**Pull request merged**
