### PR TITLE
Add option to make tar work on NFS

### LINKED ISSUE #381: tar does not always work properly on shared filesystems
See [here](http://ensode.net/roller/dheffelfinger/entry/tar_failing_with_error_message) for a possible solution (flag `--ignore-failed-read` for the `tar` command).

Reported problem looks like:

```
  ./slc6_x86-64/defaults-release/v1-1: file changed as we read it
```

### PR DESCRIPTION
**Pull request by dberzano**
Fixes #381

### CODE REVIEW

**Comment by dberzano** [comment]
Note that we should think of the consequences of using this option on non-shared filesystems. This is not an ideal fix...

**Comment by lietava** [comment]
How can I download this branch ? I am trying:
 pip install --user rl https://github.com/dberzano/alibuild.git@fix-tar-nfs#egg=alibuild
It is not working ...
Thanks, Roman.

**Comment by dberzano** [comment]
Drop the `rl` after the `--user`. Make sure you export `PYTHONUSERBASE=/path` and `PATH=$PYTHONUSERBASE/bin:$PATH` first.

**Comment by lietava** [comment]
HI Dario , still no success. Please, see below. Thanks, Roman.

 bash-4.1$ pip uninstall alibuild 
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Cannot uninstall requirement alibuild, not installed
bash-4.1$  pip install --user https://github.com/dberzano/alibuild.git@fix-tar-nfs#egg=alibuild 
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Collecting alibuild from https://github.com/dberzano/alibuild.git@fix-tar-nfs#egg=alibuild
/home/rl/mypython/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/rl/mypython/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  HTTP error 406 while getting https://github.com/dberzano/alibuild.git@fix-tar-nfs#egg=alibuild
  Could not install requirement alibuild from https://github.com/dberzano/alibuild.git@fix-tar-nfs#egg=alibuild because of error 406 Client Error: Not Acceptable for url: https://github.com/dberzano/alibuild.git@fix-tar-nfs
Could not install requirement alibuild from https://github.com/dberzano/alibuild.git@fix-tar-nfs#egg=alibuild because of HTTP error 406 Client Error: Not Acceptable for url: https://github.com/dberzano/alibuild.git@fix-tar-nfs for URL https://github.com/dberzano/alibuild.git@fix-tar-nfs#egg=alibuild
bash-4.1$ echo $PATH
/bin:/home/rl/mypython/bin:/home/rl/bin:/usr/local/bin:/usr/bin
bash-4.1$

**Comment by dberzano** [comment]
`pip install --user git+https://github.com/dberzano/alibuild.git@fix-tar-nfs`. Have a look at the [pip documentation](https://pip.pypa.io/en/stable/) for further information.

**Comment by lietava** [comment]
Thanks, I installed fix-tar-nfs. 
aliroot still does not compile. It stops at tar even with ignore-failed-read ...
PLease, see below.
Roman.

 DEBUG:AliPhysics:ali-master: + PACKAGE_WITH_REV=defaults-release-v1-1.slc6_x86-64.tar.gz
DEBUG:AliPhysics:ali-master: + tar -C /disk/moose/alice/software/alisl6/sw/INSTALLROOT/6196710596f85e564da2aa10112d2928421e4b42 --ignore-failed-read -c -z -f /disk/moose/alice/software/alisl6/sw/TARS/slc6_x86-64/store/61/6196710596f85e564da2aa10112d2928421e4b42/defaults-release-v1-1.slc6_x86-64.tar.gz.processing .
DEBUG:AliPhysics:ali-master: tar: ./slc6_x86-64/defaults-release/v1-1: file changed as we read it
DEBUG:AliPhysics:ali-master: tar: ./slc6_x86-64/defaults-release: file changed as we read it
DEBUG:AliPhysics:ali-master: tar: ./slc6_x86-64: file changed as we read it
DEBUG:AliPhysics:ali-master: tar: .: file changed as we read it

**Comment by dberzano** [comment]
Is this the end of the log? Are you sure it stops there? I just want to be sure.

**Comment by lietava** [comment]
DEBUG:AliPhysics:ali-master: + PACKAGE_WITH_REV=defaults-release-v1-1.slc6_x86-64.tar.gz
DEBUG:AliPhysics:ali-master: + tar -C /disk/moose/alice/software/alisl6/sw/INSTALLROOT/6196710596f85e564da2aa10112d2928421e4b42 --ignore-failed-read -c -z -f /disk/moose/alice/software/alisl6/sw/TARS/slc6_x86-64/store/61/6196710596f85e564da2aa10112d2928421e4b42/defaults-release-v1-1.slc6_x86-64.tar.gz.processing .
DEBUG:AliPhysics:ali-master: tar: ./slc6_x86-64/defaults-release/v1-1: file changed as we read it
DEBUG:AliPhysics:ali-master: tar: ./slc6_x86-64/defaults-release: file changed as we read it
DEBUG:AliPhysics:ali-master: tar: ./slc6_x86-64: file changed as we read it
DEBUG:AliPhysics:ali-master: tar: .: file changed as we read it
DEBUG:AliPhysics:ali-master: 
ERROR:AliPhysics:ali-master: Error while executing /disk/moose/alice/software/alisl6/sw/SPECS/slc6_x86-64/defaults-release/v1-1/build.sh on `eprexa.ph.bham.ac.uk'.
ERROR:AliPhysics:ali-master: Log can be found in /disk/moose/alice/software/alisl6/sw/BUILD/defaults-release-latest/log.
ERROR:AliPhysics:ali-master: Please attach this file if you intend to request support.
ERROR:AliPhysics:ali-master: Build directory is /disk/moose/alice/software/alisl6/sw/BUILD/defaults-release-latest/defaults-release.
bash-4.1$ ls /disk/moose/alice/software/alisl6/sw/BUILD/defaults-release-latest
defaults-release  log
bash-4.1$ ls /disk/moose/alice/software/alisl6/sw/BUILD/defaults-release-latest/log 
/disk/moose/alice/software/alisl6/sw/BUILD/defaults-release-latest/log
bash-4.1$ ls /disk/moose/alice/software/alisl6/sw/BUILD/defaults-release-latest/log 
/disk/moose/alice/software/alisl6/sw/BUILD/defaults-release-latest/log
bash-4.1$

**Comment by dberzano** [comment]
OK thanks, it really looks like it's a NFS problem - some metadata is cached when tar does the first query, then these metadata change and tar complains. I don't know exactly how to address this at the moment (if you have ideas please share).

Note: please use Markdown formatting for GitHub comments, to make them more readable :-)

**Comment by lietava** [comment]
log is empty:
bash-4.1$ ls -l /disk/moose/alice/software/alisl6/sw/BUILD/defaults-release-latest/
total 0
drwxr-xr-x. 2 rl alice 0 Nov 23 10:31 defaults-release
-rw-r--r--. 1 rl alice 0 Nov 23 10:31 log

**Comment by lietava** [comment]
ok, thanks, let you know :).  The road with moving is closed ? R.

**Comment by dberzano** [comment]
Let's try to fix the NFS problem first. Can you try now?

**Comment by lietava** [comment]
It is not crashing on tar. But it seems very slow. One compilation was interrupted during night for other reasons. So still in progress. Let you know.

**Comment by dberzano** [comment]
No wonder it's slow on NFS :-)

**Comment by ktf** [comment]
Indeed. Try also to limit the parallel tasks with -j 1.

--
Ciao,
Giulio

**Comment by lietava** [comment]
Giulio, where can I set -j 1 ? aliBuild does not see it as option.
export MJ=1  ?
R.

**Comment by lietava** [comment]
BTW, still not succeed. Starting from fresh now. R.

**Comment by dberzano** [comment]
@lietava: `aliBuild -j 1 build PackageName` *does* work. Maybe you have specified `-j 1` between `build` and `PackageName`? Can you please be more detailed with your reports? How does it fail? `tar` problem or something else?

**Comment by lietava** [comment]
Dario, sorry. More detailed report: It is incredible slow. So one iterations take me a day. This morning it seems to finish compilation but I was not able to start aliroot. I might have screwed some directories. So I am starting from fresh now removing everything. tar seems not to be a problem. But I confirm when I succeed to compile and start aliroot OR I will be able to identify problem.
Thanks, R.

**Comment by lietava** [comment]
Dario, it is working. Thanks a lot ! Roman.

**Comment by dberzano** [comment]
This is great news, thanks for your feedback!

**Comment by ktf** [comment]
Didn't we merge this?

**Comment by dberzano** [comment]
The approach works, however there might be a better way to detect if `tar` supports that option. Let me think of something.

**Comment by dberzano** [comment]
I prefer this new iteration. I have tested it on Mac (where `--ignore-failed-read` is not supported by bsdtar) and Linux. This new option tests directly if the option is supported by whatever `tar` is available from the `$PATH` without assuming that it is available on Linux and not on macOS. We can merge this now if you want.

**Comment by ktf** [comment]
Can you run the check only once per call? Kinda like we do for the pgzip implementation. I think it makes sense to have a $TAR variable defined before the script actually run.

**Comment by ktf** [comment]
Basically this https://github.com/alisw/alibuild/blob/master/aliBuild#L1203

**Comment by dberzano** [comment]
I agree for consistency reasons with the `pgzip` thing (all in all the check is not heavy at all). Let me come back on this.

**Comment by dberzano** [comment]
@ktf what about now?

**Pull request merged**
