### PR TITLE
Custom WORK_DIR instead of sw in alienv helper and support alibuild from pip

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@ktf, as requested.

**Comment by ktf** [comment]
Thanks. Since I am preparing the pip installation, you should look for alienv in `$PATH` if it's not in `alibuild/alienv`.

**Comment by dberzano** [comment]
Indeed, let me update this.

**Comment by dberzano** [comment]
@ktf this does the trick

**Pull request merged**
